[package]
name = "clidj"
version = "0.1.0"
authors = ["Ludvig Sundström <lud.sund@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vlc-rs = "0.3"
ncurses = "5.99.0"
